version: "3.8"

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - web.env
      - web_secrets.env
    ports:
      - "8000:8000"
    networks:
      - restaurant_network
    depends_on:
      - db
      - celery

  celery:
    build: .
    command: ["celery", "-A", "restaurant_project", "worker", "--loglevel=INFO"]
    env_file:
      - web.env
      - web_secrets.env
    networks:
      - restaurant_network
    depends_on:
      - rabbitmq

  db:
    image: postgres:13
    env_file:
      - db.env
      - db_secrets.env
    networks:
      - restaurant_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8.9
    env_file:
      - rabbitmq.env
      - rabbitmq_secrets.env
    hostname: my-rabbit
    networks:
      - restaurant_network
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq

networks:
  restaurant_network:
    driver: bridge

volumes:
  db_volume:
  rabbitmq_volume:
