version: "3.8"

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - web.env
      - web_secrets.env
    ports:
      - "8000:8000"
    networks:
      - restaurant_network
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - db.env
      - db_secrets.env
    networks:
      - restaurant_network
    volumes:
      - db_volume:/var/lib/postgresql/data

networks:
  restaurant_network:
    driver: bridge

volumes:
  db_volume:
