# Generated by Django 3.1.2 on 2020-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant/dish_image/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='restaurant.Allergen'),
        ),
    ]
